Fix build

diff --git a/.github/workflows/checkBuild.yml b/.github/workflows/checkBuild.yml
--- a/.github/workflows/checkBuild.yml
+++ b/.github/workflows/checkBuild.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
   push:
     branches: [ main ]
-    paths-ignore: 
+    paths-ignore:
       - '**.md'
       - '.config/**'
       - '.github/**'
@@ -12,7 +12,7 @@ on:
       - 'assets/**'
   pull_request:
     branches: [ main ]
-    paths-ignore: 
+    paths-ignore:
       - '**.md'
       - '.config/**'
       - '.github/**'
@@ -25,71 +25,71 @@ jobs:
 
     strategy:
       matrix:
-        java: [21]
-        distribution: [temurin]
+        java: [ 21 ]
+        distribution: [ temurin ]
 
     steps:
-    - uses: actions/checkout@v4
-      
-    - name: Set up JDK
-      uses: actions/setup-java@v4
-      with:
-        distribution: ${{ matrix.distribution }}
-        java-version: ${{ matrix.java }}
-        cache: 'gradle'
-      
-    - name: Build
-      run: ./gradlew build buildPlugin --info
+      - uses: actions/checkout@v4
 
-    - name: Try upload test reports when failure occurs
-      uses: actions/upload-artifact@v4
-      if: failure()
-      with:
-        name: test-reports-${{ matrix.java }}
-        path: build/reports/tests/test/**
-      
-    - name: Check for uncommited changes
-      run: |
-        if [[ "$(git status --porcelain)" != "" ]]; then
-          echo ----------------------------------------
-          echo git status
-          echo ----------------------------------------
-          git status
-          echo ----------------------------------------
-          echo git diff
-          echo ----------------------------------------
-          git diff
-          echo ----------------------------------------
-          echo Troubleshooting
-          echo ----------------------------------------
-          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && mvn -B clean package"
-          exit 1
-        fi
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: ${{ matrix.distribution }}
+          java-version: ${{ matrix.java }}
+          cache: 'gradle'
 
-    - name: Upload plugin files
-      uses: actions/upload-artifact@v4
-      with:
-        name: plugin-files-java-${{ matrix.java }}
-        path: build/libs/external-java-formatter-intellij-plugin-*.jar
-        if-no-files-found: error
+      - name: Build
+        run: ./gradlew build buildPlugin --info
+
+      - name: Try upload test reports when failure occurs
+        uses: actions/upload-artifact@v4
+        if: failure()
+        with:
+          name: test-reports-${{ matrix.java }}
+          path: build/reports/tests/test/**
+
+      - name: Check for uncommited changes
+        run: |
+          if [[ "$(git status --porcelain)" != "" ]]; then
+            echo ----------------------------------------
+            echo git status
+            echo ----------------------------------------
+            git status
+            echo ----------------------------------------
+            echo git diff
+            echo ----------------------------------------
+            git diff
+            echo ----------------------------------------
+            echo Troubleshooting
+            echo ----------------------------------------
+            echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && mvn -B clean package"
+            exit 1
+          fi
+
+      - name: Upload plugin files
+        uses: actions/upload-artifact@v4
+        with:
+          name: plugin-files-java-${{ matrix.java }}
+          path: build/libs/plantarch-intellij-plugin-*.jar
+          if-no-files-found: error
 
   code-style:
     runs-on: ubuntu-latest
 
     strategy:
       matrix:
-        java: [21]
-        distribution: [temurin]
+        java: [ 21 ]
+        distribution: [ temurin ]
 
     steps:
-    - uses: actions/checkout@v4
-      
-    - name: Set up JDK
-      uses: actions/setup-java@v4
-      with:
-        distribution: ${{ matrix.distribution }}
-        java-version: ${{ matrix.java }}
-        cache: 'gradle'
+      - uses: actions/checkout@v4
 
-    - name: Run Checkstyle
-      run: ./gradlew checkstyleMain checkstyleTest -PcheckstyleEnabled=true
+      - name: Set up JDK
+        uses: actions/setup-java@v4
+        with:
+          distribution: ${{ matrix.distribution }}
+          java-version: ${{ matrix.java }}
+          cache: 'gradle'
+
+      - name: Run Checkstyle
+        run: ./gradlew checkstyleMain checkstyleTest -PcheckstyleEnabled=true
